[colors]
  # Gruvbox
  [colors.primary]
  # hard contrast background = = '#1d2021'
  background = '#282828'
  # soft contrast background = = '#32302f'
  foreground = '#ebdbb2'

  # Normal colors
  [colors.normal]
  black   = '#282828'
  red     = '#cc241d'
  green   = '#98971a'
  yellow  = '#d79921'
  blue    = '#458588'
  magenta = '#b16286'
  cyan    = '#689d6a'
  white   = '#a89984'

  # Bright colors
  [colors.bright]
  black   = '#928374'
  red     = '#fb4934'
  green   = '#b8bb26'
  yellow  = '#fabd2f'
  blue    = '#83a598'
  magenta = '#d3869b'
  cyan    = '#8ec07c'
  white   = '#ebdbb2'

  [colors.cursor]
  text = "#1e1e2e"
  cursor = "#f9f8f5"

[cursor.style]
  blinking = "Always"
[cursor]
  blink_interval = 500
  blink_timeout = 0
  thickness = 0.85 

[mouse]
  hide_when_typing = true 

[font]
  size = 10

  [font.normal]
    family = "JetBrainsMono Nerd Font"
    style = "Medium"

  [font.bold]
    family = "JetBrainsMono Nerd Font"
    style = "Bold"

  [font.italic]
    family = "JetBrainsMono Nerd Font"
    style = "Italic"

  [font.offset]
    x = 0
    y = 0

  [font.glyph_offset]
    x = 0
    y = 0

[selection]

[window]
  title = "Terminal"
  dynamic_title = false
  opacity = 1
  blur = true

  decorations_theme_variant = "Dark"

  [window.padding]
    x = 0
    y = 0

[env]
  TERM = "xterm-256color"
