[colors]

  [colors.primary]
  background = "#1e1e2e"
  foreground = "#cdd6f4"
  dim_foreground = "#7f849c"
  bright_foreground = "#cdd6f4"

  [colors.cursor]
  text = "#1e1e2e"
  cursor = "#f4b8e4"

  [colors.search.matches]
  foreground = "#1e1e2e"
  background = "#a6adc8"

  [colors.search.focused_match]
  foreground = "#1e1e2e"
  background = "#a6e3a1"

  [colors.footer_bar]
  foreground = "#1e1e2e"
  background = "#a6adc8"

  [colors.hints.start]
  foreground = "#1e1e2e"
  background = "#f9e2af"
  [colors.hints.end]
  foreground = "#1e1e2e"
  background = "#a6adc8"

  [colors.selection]
  text = "#1e1e2e"
  background = "#f5e0dc"

  [colors.normal]
  black = "#45475a"
  red = "#f38ba8"
  green = "#a6e3a1"
  yellow = "#f9e2af"
  blue = "#89b4fa"
  magenta = "#f5c2e7"
  cyan = "#94e2d5"
  white = "#bac2de"

  [colors.bright]
  black = "#585b70"
  red = "#f38ba8"
  green = "#a6e3a1"
  yellow = "#f9e2af"
  blue = "#89b4fa"
  magenta = "#f5c2e7"
  cyan = "#94e2d5"
  white = "#a6adc8"

  [colors.dim]
  black = "#45475a"
  red = "#f38ba8"
  green = "#a6e3a1"
  yellow = "#f9e2af"
  blue = "#89b4fa"
  magenta = "#f5c2e7"
  cyan = "#94e2d5"
  white = "#bac2de"

  [[colors.indexed_colors]]
  index = 16
  color = "#fab387"

  [[colors.indexed_colors]]
  index = 17
  color = "#f5e0dc"

[cursor.style]
  blinking = "Always"
[cursor]
  blink_interval = 500
  blink_timeout = 0
  thickness = 0.85 

[mouse]
  hide_when_typing = true 

[font]
  size = 12

  [font.normal]
    family = "JetBrainsMono Nerd Font"
    style = "Medium"

  [font.bold]
    family = "JetBrainsMono Nerd Font"
    style = "Bold"

  [font.italic]
    family = "JetBrainsMono Nerd Font"
    style = "Italic"

  [font.offset]
    x = 0
    y = 0

  [font.glyph_offset]
    x = 0
    y = 0

[selection]


[window]
  title = "Terminal"
  dynamic_title = false
  opacity = 0.7
  blur = true

  decorations_theme_variant = "Dark"

  [window.padding]
    x = 2
    y = 2

[env]
  TERM = "xterm-256color"
