[colors.primary]
  background = '#282828'
  foreground = '#dfbf8e'

[colors.normal]
  black   = '#665c54'
  red     = '#ea6962'
  green   = '#a9b665'
  yellow  = '#e78a4e'
  blue    = '#7daea3'
  magenta = '#d3869b'
  cyan    = '#89b482'
  white   = '#dfbf8e'

[colors.bright]
  black   = '#928374'
  red     = '#ea6962'
  green   = '#a9b665'
  yellow  = '#e3a84e'
  blue    = '#7daea3'
  magenta = '#d3869b'
  cyan    = '#89b482'
  white   = '#dfbf8e'

[colors.cursor]
  text = "#1e1e2e"
  cursor = "#f9f8f5"

[cursor.style]
  blinking = "Always"
[cursor]
  blink_interval = 500
  blink_timeout = 0
  thickness = 0.85 

[mouse]
  hide_when_typing = true 

[font]
  size = 14

  [font.normal]
    family = "JetBrainsMono Nerd Font"
    style = "Medium"

  [font.bold]
    family = "JetBrainsMono Nerd Font"
    style = "Bold"

  [font.italic]
    family = "JetBrainsMono Nerd Font"
    style = "Italic"

  [font.offset]
    x = 0
    y = 0

  [font.glyph_offset]
    x = 0
    y = 0

[selection]

[window]
  title = "Terminal"
  dynamic_title = false
  opacity = 0.8
  blur = true

  decorations_theme_variant = "Dark"

  [window.padding]
    x = 10
    y = 0

[env]
  TERM = "xterm-256color"
